// Generated by https://quicktype.io

export interface SiteAbout {
  content: string[];
  items:   Item[];
}

export interface Item {
  title:      string;
  description: string;
  urlSite:    string;
  urlImg:   string;
  details:    string;
}
